// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45YEHr0w1zOcczNS1bb90nDR0LLW0ioA',
    appId:
        '1:519697646770:web:YOUR_REAL_WEB_APP_ID', // ← Replace with real web app ID
    messagingSenderId: '519697646770',
    projectId: 'krishideep-cd50e',
    authDomain: 'krishideep-cd50e.firebaseapp.com',
    storageBucket: 'krishideep-cd50e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mH-4Zjy6H5-ITOukCszc_9NBFu_es9I',
    appId: '1:519697646770:android:7279264b3232fd208c35ab',
    messagingSenderId: '519697646770',
    projectId: 'krishideep-cd50e',
    storageBucket: 'krishideep-cd50e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45YEHr0w1zOcczNS1bb90nDR0LLW0ioA',
    appId: '1:519697646770:ios:krishideep-ios-app',
    messagingSenderId: '519697646770',
    projectId: 'krishideep-cd50e',
    storageBucket: 'krishideep-cd50e.appspot.com',
    iosBundleId: 'com.example.krisi_deep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC45YEHr0w1zOcczNS1bb90nDR0LLW0ioA',
    appId: '1:519697646770:ios:krishideep-macos-app',
    messagingSenderId: '519697646770',
    projectId: 'krishideep-cd50e',
    storageBucket: 'krishideep-cd50e.appspot.com',
    iosBundleId: 'com.example.krisi_deep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC45YEHr0w1zOcczNS1bb90nDR0LLW0ioA',
    appId: '1:519697646770:web:krishideep-web-app',
    messagingSenderId: '519697646770',
    projectId: 'krishideep-cd50e',
    authDomain: 'krishideep-cd50e.firebaseapp.com',
    storageBucket: 'krishideep-cd50e.appspot.com',
  );
}
